# Generated by Django 5.2 on 2025-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
